README.md
Sources/carton/Commands/Dev.swift

- this add an optional flag to the `dev` command from `carton` to enable passing a `destination.json` file to the `swift build` call
- this requires that the toolchain referenced in the `destination.json` file is consistent with the one used by the `carton` process.
- it enables the importing of the `Foundation` module amongst others when running `carton dev`

Add --destination option to the `carton dev` command

---

Sources/carton/Commands/Versions.swift
Sources/carton/Toolchain/ToolchainManagement.swift

Move previous description to #15 .
This PR implements `carton sdk versions` to list all installed sdks.

Support `carton sdk versions`

---

Package.swift

The new version contains important bug fixes that prevent memory leaks.

Bump OpenCombine version to 0.10.0

---

Package.swift

This comes after I was reminded that we're using an old version in https://github.com/swiftwasm/carton/pull/33.

Use `from` instead of `upToNextMinor` for OpenCombine

---

Package@swift-5.2.swift
Sources/CartonHelpers/ProcessRunner.swift
Sources/SwiftToolchain/ProgressAnimation.swift
Sources/SwiftToolchain/ToolchainManagement.swift
Sources/carton/Combine/Watcher.swift
Sources/carton/Commands/Dev.swift
Sources/carton/Commands/Test.swift
Sources/carton/Server/Server.swift

@ddddxxx with conditional dependencies available in Swift 5.3 I think this resolves the issue that you mentioned in https://github.com/swiftwasm/Tokamak/pull/170. The binary size is only reduced from 23 MB to 21 MB though, I expected a bit more...

Use Combine instead of OpenCombine where possible

---

Sources/SwiftToolchain/Package.swift
Sources/SwiftToolchain/Toolchain.swift
Sources/carton/Commands/Dev.swift
TestApp/CustomPathTarget/text.swift
TestApp/Package.swift

Sources are added per target and use a custom path if provided by the package manifest. This should fix #1 !

Add sources to watcher per target

---

Sources/SwiftToolchain/Toolchain.swift

Thanks to this the presence of `LinuxMain.swift` file is no longer needed.

Always pass --enable-test-discovery to swift build

---

.vscode/tasks.json
Package.resolved
Sources/carton/Commands/Test.swift

Refines the `carton test` command as a continuation of #42 work.

Add `list` flag and `testCases` argument to `test`

---

Sources/CartonHelpers/ProcessRunner.swift
Sources/carton/Helpers/Expectation.swift

Resolves #56.
Also, a brief doc comment is added to the `Equality` assertions helper type.

Propagate test build/run failures in the exit code

---

.vscode/tasks.json
Sources/CartonHelpers/ProcessRunner.swift
Sources/SwiftToolchain/Toolchain.swift
Sources/carton/Combine/Watcher.swift
Sources/carton/Helpers/FileSystem.swift

Currently, when `carton dev` is launched in any subdirectory of the package not containing `Package.swift` it crashes. It's caused by `traverseRecursively` precondition failing when a non-directory (or non-existent) path is passed to it. I think `traverseRecursively` can handle non-existing paths well by returning an empty array, and the path itself when it's a file and not a directory. Thus the precondition check is not needed at all.
Non-existent paths were created due to a wrong assumption that the root package directory is always the current directory. This is now fixed by adding a new `inferManifestDirectory` function, which correctly calculates absolute paths of source directories before passing them to the watcher.
Additionally the watcher code in the `TSCBasic` code has its own …

Fix watcher crashing in package subdirectories

---

Sources/CartonHelpers/TerminalController.swift
Sources/SwiftToolchain/Toolchain.swift
Sources/carton/Commands/Dev.swift
Sources/carton/Server/Server.swift

This adds a `--verbose/-v` flag to `carton dev`.
When enabled, logging acts the same as before this PR.
Otherwise, the screen is cleared before starting, and after every rebuild. This keeps the most recent diagnostics visible, while keeping the terminal relatively clean. It also switches the Vapor `Environment` to `"production"` to only show logs >= notices.
`-Xswiftc -color-diagnostics` is also passed to the Swift compiler for both levels.
Let me know if any of this is behavior isn't desired.

Add verbose/concise logging levels

---

.github/workflows/swift.yml

This should unblock https://github.com/swiftwasm/carton/pull/74 as we currently can't install sqlite headers as a part of the build process with that action.
Standard GitHub Actions Ubuntu 20.04 VMs already supply Swift 5.2, so there's no strong reason to keep using 3rd-party actions for Linux builds.

Avoid using 3rd-party action for the Linux build

---

Sources/SwiftToolchain/Toolchain.swift
Sources/SwiftToolchain/ToolchainManagement.swift

Fix #72.
If you are installing an invalid version, It'll now throw an `InvalidVersion` error and the output will be more friendly.

Fix crash caused by use of `try!` while installing invalid version

---

Sources/carton/Model/Template.swift

As the Tokamak project has been moved to a separate [TokamakUI organization](https://github.com/TokamakUI), the template has been updated accordingly.

Update `tokamak` template for the new TokamakUI org

---

Sources/CartonHelpers/DefaultToolchain.swift
Sources/carton/Commands/Bundle.swift

The latest 5.3 toolchain snapshot fixes release builds of Tokamak. 
We no longer need `carton bundle` to produce debug builds by default, so it closes #103 as outdated.
Formatting of a `carton bundle` message is fixed as it didn't have a required trailing newline.

Bump default toolchain version, fix release builds

---

README.md
Sources/CartonHelpers/DefaultToolchain.swift
Sources/SwiftToolchain/Package.swift
Sources/SwiftToolchain/Toolchain.swift
Sources/carton/Commands/Dev.swift
Sources/carton/Server/Application.swift
Sources/carton/Server/Server.swift
TestApp/.swift-version
TestApp/Package.resolved
TestApp/Package.swift
TestApp/Sources/TestApp/data.json
TestApp/Sources/TestApp/main.swift

This change requires `wasm-5.3-SNAPSHOT-2020-09-08-a` or later, therefore the default toolchain version has been bumped.
Implements the `carton dev` part of #38, `carton bundle` support will be implemented in a future PR.

Implement support for static resources in `carton dev`

---

README.md
Sources/carton/Commands/Dev.swift
Sources/carton/Server/Server.swift

Resolves #92.
While there [a lot](https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/openBrowser.js) [more](https://github.com/sindresorhus/open) options possible to cram here I think this is a decent start. Perhaps an opportunity for a cross-platform Swift launcher µ framework?

Automatically open a browser window when Dev Server starts

---

Package.resolved
Package.swift
Package@swift-5.2.swift
Sources/CartonHelpers/DiagnosticsParser.swift
Sources/CartonHelpers/InteractiveWriter.swift
Sources/CartonHelpers/ProcessRunner.swift
Sources/CartonHelpers/TerminalController.swift
Sources/SwiftToolchain/Toolchain.swift
Sources/carton/Commands/Dev.swift
Sources/carton/Server/Server.swift

The output from the Swift compiler can be pretty verbose. This adds better formatting and syntax highlighting to the compiler's output (modeled after the error messages of React).
I also modified the screen-clearing to reset the scrollback so you can easily find the first error without scrolling past it.

Pretty print diagnostics

---

.github/workflows/swift.yml
install_ubuntu_deps.sh

`sudo` is not always available in Docker containers, so we should assume users will run the script itself with `sudo` when needed.

Remove sudo usage from `install_ubuntu_deps.sh`

---

.github/workflows/swift.yml

Now that Big Sur is available on GitHub Actions, we can get more certainty that everything works with the new OS (on Intel hardware for now).

Build on macOS Big Sur with GitHub Actions

---

Dockerfile
Sources/CartonHelpers/DefaultToolchain.swift
Sources/SwiftToolchain/Toolchain.swift
Sources/SwiftToolchain/ToolchainInstallation.swift
Sources/SwiftToolchain/ToolchainManagement.swift

`carton` can't install toolchains from `.pkg` archives at the moment, and the latest toolchain snapshots are distributed exclusively as signed `.pkg` for macOS.
Parts of `ToolchainManagement.swift` related to toolchain installation were moved to `ToolchainInstallation.swift`.

Add support for signed `.pkg` archives on macOS

---

Sources/CartonHelpers/ProcessRunner.swift

Without this patch `ProcessRunner` output pollutes non-interactive terminals such as GitHub Actions logs, where `loadingMessage` value is printed multiple times in a row for every compiled file.

Avoid repeated `loadingMessage` in `ProcessRunner`

---

Sources/SwiftToolchain/Toolchain.swift
package-lock.json
package.json

Other than a simple bump, we shouldn't check for the revision anymore. Now the recommended way to specify this dependency is only with a semantic version constraint.

Bump JavaScriptKit to 0.8, stop checking revision

---

.github/workflows/swift.yml
Package.swift
Sources/CartonHelpers/DiagnosticsParser.swift
Tests/CartonTests/CartonTests.swift
Tests/CartonTests/XCTestManifests.swift
Tests/LinuxMain.swift

Previously, an error message such as:
```
ERROR   invalid redeclaration of 'resolve(in:)'
58 |    public func resolve(in environment: EnvironmentValues) -> _Font {
```
would be output:
```
ERROR   invalid redeclaration of 'resolve(in
58 |    public func resolve(in environment: EnvironmentValues) -> _Font {
```
if the message had a colon.

Fix error message output

---

.github/workflows/swift.yml

For some reason GHA Big Sur hosts no longer have Xcode 12.1 installed as evidenced by CI failures in #141 and #144. We can use Xcode 12.2 instead.

Use Xcode 12.2 on macOS Big Sur

---

Sources/CartonHelpers/DefaultToolchain.swift
Sources/SwiftToolchain/Toolchain.swift

Latest toolchains produce binaries with the `.wasm` extension which `carton` can't handle yet.

Fix handling of binaries with `.wasm` extension

---

.vscode/tasks.json
Dockerfile
Sources/SwiftToolchain/Toolchain.swift

Every Swift package with test targets has an implicit test product with `"\(package.name)PackageTests"` name. `swift build --build-tests` builds all products in a given package including the implicit test product. This doesn't work in situations where some of the products can't be compiled for Wasm, even when they are excluded with `condition: .when(platforms: [.macOS, .linux])` from test dependencies. This prevents tests from being built at all in such packages. OpenCombine is the primary victim of this problem.
Fortunately, the implicit test product can be accessed through the `--product` option passed to `swift build`. When using that option, only the test product and its dependencies are built. Products (and therefore their underlying targets) that aren't needed for tests are excluded …

Build only test product and its deps for testing

---

Sources/CartonHelpers/Parsers/TestsParser.swift

Currently test report outputs time as something like `0.17200000000000013s, estimated 1s`. This is not very readable, so maybe something like `0.17s` would be better?

Format testing time to two decimal places

---

Sources/CartonHelpers/DefaultToolchain.swift
Sources/SwiftToolchain/Toolchain.swift

After https://github.com/apple/swift-package-manager/pull/3013 was merged and cherry-picked for our 5.3 snapshots (starting with `wasm-5.3-SNAPSHOT-2020-11-02-a`), `carton test` needs to handle the `.wasm` extension in test products.

Fix handling of test products with .wasm extension

---

Dockerfile
Sources/CartonHelpers/DefaultToolchain.swift

Update Dockerfile to use ghcr.io/swiftwasm/swift as base image and update default toolchain version as 5.3 release

Use ghcr.io/swiftwasm/swift as base image

---

Sources/SwiftToolchain/Toolchain.swift
Sources/carton/Model/Template.swift

Tokamak 0.6.0 is not released yet, but I will do it as soon as https://github.com/TokamakUI/Tokamak/pull/155 is approved.

Bump versions of libraries in `Template.swift`

---

Sources/CartonHelpers/Parsers/ChromeStackTrace.swift
Sources/CartonHelpers/Parsers/FirefoxStackTrace.swift
Sources/CartonHelpers/Parsers/SafariStackTrace.swift
Sources/CartonHelpers/StackTrace.swift
Sources/SwiftToolchain/DestinationEnvironment.swift
Sources/carton/Server/Server.swift
Tests/CartonTests/StackTraceTests.swift
entrypoint/dev.js

I made `location` optional because Safari doesn’t report it for some reason. There’s a bit of duplication between the stack trace parsers but I don’t think that’s a big problem.
I’ve also changed the behavior to log when an error occurs in an unsupported browser, and to provide a sample stack trace that we can attempt to parse.

Add support for Chrome and Safari stack traces

---

Dockerfile

We already run these tests on Ubuntu as a part of separate CI jobs.

Avoid running tests while building the Docker image

---

README.md

Just a paragraph about browser testing removed. It is no longer relevant since this feature has been implemented.

Update the "Roadmap" section in `README.md`

---

Tests/CartonCommandTests/InitCommandTests.swift

Pretty straight forward test. I am considering removing the full source comparison and only looking for "import TokamakDOM" and then including a lookup in the Package.swift file for the "tokamak repository"

Add `carton init` with template test. Supports #99

---

.github/workflows/swift.yml
Tests/LinuxMain.swift

This fixes the issue with Linux builds, as Linux CI hosts were updated to Swift 5.4 which no longer supports testing with release builds.

Avoid building in `release` mode when testing

---

README.md
install_ubuntu_deps.sh

Fix Ubuntu deps, clarify Linux support in README

---

.github/workflows/swift.yml
Package.swift
Sources/CartonHelpers/DefaultToolchain.swift
Sources/CartonHelpers/Version.swift
Sources/CartonKit/Model/Template.swift
Tests/CartonCommandTests/BundleCommandTests.swift
Tests/CartonCommandTests/CommandTestHelper.swift
Tests/CartonCommandTests/DevCommandTests.swift
Tests/CartonCommandTests/InitCommandTests.swift
Tests/CartonCommandTests/SDKCommandTests.swift
Tests/Fixtures/Milk/Package.resolved
Tests/Fixtures/Milk/Package.swift
package-lock.json
package.json

In this version we start using SwiftWasm 5.4.0 and Tokamak 0.8 by default. Other related dependencies have been updated.

Bump version to 0.11.0, update dependencies

---

Sources/SwiftToolchain/Toolchain.swift

Without this change you'd see `warning: '--enable-test-discovery' option is deprecated; tests are automatically discovered on all platforms` when building.

Disable `--enable-test-discovery` for old versions

---

Package.resolved
Package.swift
Sources/CartonHelpers/DefaultToolchain.swift
Sources/CartonHelpers/Version.swift
Sources/SwiftToolchain/ToolchainInstallation.swift
Tests/Fixtures/TestApp/Package.resolved
Tests/Fixtures/TestApp/Package.swift
package-lock.json
package.json

`async-http-client` package is now pinned to 1.6.4, as 1.7.0 and later versions caused issues with toolchain downloads (see https://github.com/swift-server/async-http-client/issues/488 for more details).
I've also updated toolchain downloader code to bubble up download errors, which previously were hidden and made it very hard to diagnose these issues.

Use SwiftWasm 5.5.0, bump version to 0.12.0

---

Dockerfile
Package.resolved
Package.swift

Our `Dockerfile` should be updated to depend on SwiftWasm 5.5.
Additionally, Async HTTP Client has fixed the toolchain downloads issue in 1.8.1, I'm setting it as a minimum version in `Package.swift` here.

Bump SwiftWasm to 5.5 in `Dockerfile`, bump AHC

---

Dockerfile

Currently https://github.com/swiftwasm/carton/pull/273 fails because of `libtinfo.so.5: cannot open shared object file: No such file or directory` error happening during Wasmer installation. This should be resolved by installing `libncurses5` package explicitly in `Dockerfile`.

Fix Wasmer installation issues in `Dockerfile`

---

.github/workflows/docker.yml
.github/workflows/swift.yml

This makes it possible to test latest `carton` Docker builds from the `main` branch.

Build `main` Docker images on every push to `main` branch

---

Dockerfile
Package.resolved
Package.swift

Resolves #274.
On macOS release binary grows from 27MB to 40MB.

Statically link with `SwiftPMDataModel` library

---

install_ubuntu_deps.sh

Fixes #287 
Not installed by default on all Ubuntu-based distributions.

Add libsqlite3-dev dependency

---

Sources/CartonKit/Server/Server.swift
Sources/SwiftToolchain/Toolchain.swift

If we run `carton dev` on a package with a Swift 5.4-style `executableTarget`, carton cannot infer the source path and will crash trying to initialize FSWatch with an empty paths array.
```
TSCUtility/FSWatch.swift:46: Precondition failed
```
Fix this issue for executable targets and prevent similar issues with empty arrays.

Fix crash for packages with `executableTarget`

---

Package.resolved
Package.swift
Sources/CartonHelpers/Parsers/DiagnosticsParser.swift
Sources/CartonKit/Server/Server.swift
Sources/SwiftToolchain/Manifest.swift
Sources/SwiftToolchain/Toolchain.swift

Upgrades libSwiftPM from 5.5 to 5.6 + related dependencies' versions (tools-support-core and swift-argument-parser). Fixes #285.
This changes the parsing strategy to rely on libSwiftPM to directly invoke swiftc and parse a compiled manifests' output. While I expected the output of `swift package dump-package` to be more stable than `PackageDescription`'s JSON output, the opposite is true, and at least between 5.5 and 5.6 that format is backwards compatible. We may have to revisit this if this internal format breaks.
```mermaid
sequenceDiagram
carton w/ libSwiftPM->>SwiftWasm SwiftPM: (shell) swift package dump-package
SwiftWasm SwiftPM->>SwiftWasm swiftc: build manifest for host platform with host SDK
SwiftWasm swiftc->>SwiftWasm SwiftPM: compiled host manifest
SwiftWasm …
```

Use libSwiftPM 5.6 to parse manifests

---

.github/workflows/swift.yml
Tests/CartonCommandTests/CommandTestHelper.swift
Tests/CartonCommandTests/DevCommandTests.swift

There are issues with binding 0.0.0.0 address on macOS 12, I'm dropping the corresponding argument from tests in f24d39e8f8bf19e39056bdd51fd840600598ebec. Also seeing issues with Ubuntu 18.04, even though all tests seem to be passing. Dropping it as an old version from CI as well.

Add macOS 12 and Xcode 13.3 to CI matrix

---

Sources/CartonCLI/Commands/Bundle.swift

Since https://github.com/swiftwasm/carton/pull/301, carton started passing `--debuginfo` to wasm-opt, but it still strips all custom sections before it.

Don't strip custom sections when --debug-info

---

CHANGELOG.md
Sources/CartonHelpers/Version.swift
package-lock.json
package.json

Ideally we'd like to include new JSKit and SwiftWasm releases, but I think it makes more sense to wait for new JSKit release a bit more and to test things more thoroughly. Also, the watcher bug is still not fixed.
On the other hand, `--debug-info` has been highly requested by our users, so nothing prevents us from releasing 0.13.0 right now, and 0.14.0 with new JSKit/Tokamak and SwiftWasm 5.6 later.

Bump version to 0.13.0, update `CHANGELOG.md`

---

README.md

New CLI options added in 0.13.0 weren't described in `README.md`, let's fix that.

Describe `--debug-info` and `-Xswiftc` in `README.md`

---

Sources/SwiftToolchain/Toolchain.swift
Tests/CartonCommandTests/TestCommandTests.swift

This enables reactor model only when not building as a command, fixes https://github.com/swiftwasm/carton/issues/313
The breakage happened and was silenced in https://github.com/swiftwasm/carton/pull/310

Fix "No export `_start` found in the module" error in `carton test` 

---

entrypoint/bundle.js
entrypoint/dev.js
entrypoint/test.js

This PRs just basically apply the same patch that was done in the WasmTransformer repo. https://github.com/swiftwasm/WasmTransformer/blob/main/Fixtures/index.js#L4-L27
It is overriding the implementation of `clock_res_get` in order to solve a memory issue.
It is applied to all the entry points that `carton` has.
This PR should closes #321 .
Thanks

Override clock_res_get function from wasmer/wasi-js to fix memory issue

---

Sources/CartonKit/Model/Template.swift

Basic `target` is now deprecated in Swift 5.6 package manifests.

Fix 5.6 template: use `executableTarget`

---

.swiftlint.yml
Sources/CartonCLI/Commands/Bundle.swift
Sources/CartonHelpers/FileSystem.swift
Sources/CartonKit/Server/Application.swift
Sources/CartonKit/Server/Server.swift

Resolves https://github.com/swiftwasm/carton/issues/175.
I initially thought we should parse `Package.swift` manifests of the whole dependency tree to collect paths to resources from them, but now I'm not even sure that SwiftPM provides an API for this.
Much simpler solution is to serve with `dev` and copy with `bundle` all directories with `.resources` suffixes in the build directory. I think it's quite impossible to stumble upon unrelated directories with this approach, while it still resolves the issue as intended, in my opinion.

Serve all available resources with `dev`/`bundle`

---

README.md

This should make it easier for people to use older versions if they'd like to.

Add `carton`/SwiftWasm/JSKit compat matrix to `README.md`

---

README.md

Resolves https://github.com/swiftwasm/carton/issues/322.

Clarify `--environment` option for `carton test` in `README.md`

---

Package.resolved
Package.swift
Sources/CartonCLI/Commands/Bundle.swift
Sources/CartonCLI/Commands/Dev.swift
Sources/CartonCLI/Commands/Test.swift
Sources/SwiftToolchain/BuildFlavor.swift
Sources/SwiftToolchain/Builder.swift
Sources/SwiftToolchain/DestinationEnvironment.swift
Sources/SwiftToolchain/Toolchain.swift

This PR includes:
- Refactoring for the consistency of use of `DestinationEnvironment` and `Environment`
- And fix for `JavaScriptBigIntSupport` compatibility issue: Close https://github.com/swiftwasm/carton/issues/326

Fix JavaScriptBigIntSupport compatibility issue

---

Sources/CartonKit/Server/Server.swift
Tests/Fixtures/NodeJSKitTest/.gitignore

After switching to `async`/`await` the value of `isBuildCurrentlyRunning` wasn't correctly reset, which led to issues. By resetting the variable in `defer` we guarantee that it will be reset even when errors are thrown.
Resolves #339.

Fix watcher breakage on failed builds

---

Sources/CartonHelpers/FileSystem.swift

`FileSystem.isDirectory` returns `false` when running it on broken symlinks, which breaks Node.js tests flow. We should be able to clean up all symlinks, even broken ones. Other we can't create new correct symlinks because broken symlinks already exist at those paths.

Fix symlinks not fully cleaned up in Node.js tests

---

Sources/CartonCLI/Commands/TestRunners/NodeTestRunner.swift

Because of the lack of this check the entrypoint files weren't unpacked when missing on `carton test --environment node` runs.

Add missing check for Node.js entrypoint

---

Sources/CartonKit/Server/Application.swift

The output of production-scale test suites couldn't fit within [the default frame size limit 16kb](https://github.com/vapor/vapor/blob/50599e242043edcc2ed79b2b067233efef65dbd3/Sources/Vapor/Routing/RoutesBuilder%2BWebSocket.swift#L9)...

Stop limiting WS frame size to 16kb for large number of test suites

---

README.md
Sources/CartonCLI/Commands/Bundle.swift
Tests/CartonCommandTests/BundleCommandTests.swift

I am trying to implement an `esbuild` plugin that calls into `carton`. My plan was to call `carton bundle --debug` to get a quick development build and then extract that command's output for use in our esbuild project.
Unfortunately, `carton bundle` still runs `wasm-opt` even on a debug build, which takes 5-10s for our project. The only alternative I can see is `carton dev`, but that runs the dev server / watcher, which we don't want either for a one-off build.
Since changing the behaviour of `carton bundle --debug` to _not_ run `wasm-opt` may cause issues with backwards compatibility, @MaxDesiatov suggested we add a command line option `--wasm-optimizations {size, none}` instead, allowing users to specifically opt out of this behaviour.
The current PR implements the new …

Add option to disable wasm optimizations

---

Package.swift
README.md
Sources/CartonCLI/Commands/Dev.swift
Sources/CartonCLI/Commands/Test.swift
Sources/CartonCLI/Commands/TestRunners/BrowserTestRunner.swift
Sources/CartonKit/Server/Server.swift
Sources/WebDriverClient/WebDriverClient.swift
Tests/CartonCommandTests/TestCommandTests.swift
Tests/WebDriverClientTests/WebDriverClientTests.swift

`carton test --environment defaultBrowser` only works on macOS or X Window systems, so tests using browser APIs cannot be run on CI easily. Add a headless test runner based on WebDriver.
- Add `WebDriverClient` module, which is a thin client of W3C WebDriver: https://w3c.github.io/webdriver/
- Add `--headless` option to `carton test`

Headless test runner

---

.github/workflows/swift.yml
Dockerfile
install_ubuntu_deps.sh

Reverts swiftwasm/carton#343
As reported by @kateinoigakukun:
> after adding --static-swift-stdlib, carton init and other commands started hanging.
> It seems something wrong in Foundation or global executor. The min repro for the hang is here
> https://gist.github.com/kateinoigakukun/a3ee55fa2480a46959211c53de862131

Revert "Use `--static-swift-stdlib` for easier distribution on Linux"

---

Sources/CartonCLI/Commands/Bundle.swift
Sources/CartonCLI/Commands/TestRunners/BrowserTestRunner.swift
Sources/CartonHelpers/DefaultToolchain.swift
Sources/SwiftToolchain/Manifest.swift
Sources/SwiftToolchain/Toolchain.swift
Tests/CartonTests/CartonTests.swift

Currently carton itself builds with (host)Swift 5.6, can build SwiftWasm projects with latest 5.7 snapshot.
Still some work needed to make carton build with (host)Swift 5.7.

Toolchain changes for 5.7

---

Sources/CartonCLI/Commands/TestRunners/BrowserTestRunner.swift

[Some jobs](https://github.com/swiftwasm/carton/actions/runs/3049464466/jobs/4915562336) failed because of swiftlint.
I disabled the rule for that part, is there another way?

Ignore force_try swift-lint rule where in defer.

---

Sources/CartonKit/Model/Template.swift
Tests/CartonCommandTests/InitCommandTests.swift

It can be used the @main attribute if the filename is App.swift. like SwiftUI.
Is there a reason that filename is main.swift?

Use @main attributes

---

Package.resolved
Package.swift
Sources/CartonCLI/Commands/Bundle.swift
Sources/SwiftToolchain/Manifest.swift
Sources/SwiftToolchain/Toolchain.swift
Tests/CartonCommandTests/CommandTestHelper.swift
Tests/CartonTests/CartonTests.swift

This allows building packages requiring tool version 5.7.

Update SwiftPM library version to 5.7

---

Sources/CartonKit/Model/Template.swift

In Package.swift of template project, its dependency is declared with [package(name:url:from:)](https://developer.apple.com/documentation/packagedescription/package/dependency/package(name:url:from:)) which has been already deprecated so that Xcode show warining.
<image src="https://user-images.githubusercontent.com/7476703/193413236-5325e91b-f5a2-42d7-b525-802933574e21.png" width="300" />
This PR replace the method with [package(url:from:)](https://developer.apple.com/documentation/packagedescription/package/dependency/package(url:from:)) to fix the warning.

Fix SwiftPM dependency warning for template project

---

Sources/CartonCLI/Commands/SDK/Local.swift

When we have a project which does not contain .swift-version, `carton sdk local wasm-5.7.1-RELEASE` just claims that .swift-version does not exist, even though it is a valid toolchain version. I think it is inconvenient.
This PR makes to allow saving the local toolchain version even if the .swift-version is not present.

Allow to save .swift-version even .swift-version is missing

---

Sources/SwiftToolchain/ToolchainManagement.swift

On linux for aarch64 architecture, `carton sdk install` command fails with the following error.
```
- checking Swift compiler path: /root/.carton/sdk/wasm-5.7.1-RELEASE/usr/bin/swift
- checking Swift compiler path: /root/.swiftenv/versions/wasm-5.7.1-RELEASE/usr/bin/swift
Fetching release assets from https://api.github.com/repos/swiftwasm/swift/releases/tags/swift-wasm-5.7.1-RELEASE
Response contained body, parsing it now...
Response succesfully parsed, choosing from this number of assets: 6
The Swift version wasm-5.7.1-RELEASE was not found
Error: Invalid version wasm-5.7.1-RELEASE
```
The reason seemed to be a wrong download URL for that. 
( `carton sdk install` searches the download URL from https://api.github.com/repos/swiftwasm/swift/releases/tags/swift-wasm-5.7.1-RELEASE )

Fix carton sdk install on linux(aarch64)

---

.github/workflows/swift.yml

Hi `swiftwasm/carton`!
This is not an automatic, 🤖-generated PR, as you can check in my [GitHub profile](https://github.com/p-), I work for GitHub and I am part of the [GitHub Security Lab](https://securitylab.github.com/).
While performing a code search for container registry domains we noticed that this repo contains a misspelled domain name.
If a malicious actor were in control of that misspelled domain, they could potentially perform an attack on the software supply chain of this project and/or steal the credentials used to connect to the container registry (depending on how the misspelled domain name of the container registry is used - In some cases it's only a matter of wrongly tagged container images)
Please verify the changes made with this PR and check your documentation for …

Fix typo in container registry domain

---

Sources/SwiftToolchain/ToolchainManagement.swift

Close https://github.com/swiftwasm/carton/issues/394
Manually tested on amazonlinu2 and jammy
```
$ docker run -v $PWD:$PWD -w $PWD --rm -it swift:5.7-amazonlinux2 bash
- checking Swift compiler path: /root/.carton/sdk/wasm-5.7.1-RELEASE/usr/bin/swift
- checking Swift compiler path: /root/.swiftenv/versions/wasm-5.7.1-RELEASE/usr/bin/swift
Fetching release assets from https://api.github.com/repos/swiftwasm/swift/releases/tags/swift-wasm-5.7.1-RELEASE
Response contained body, parsing it now...
Response succesfully parsed, choosing from this number of assets: 6
Local installation of Swift version wasm-5.7.1-RELEASE not found
Swift toolchain/SDK download URL: https://github.com/swiftwasm/swift/releases/download/swift-wasm-5.7.1-RELEASE/swift-wasm-5.7.1-RELEASE-amazonlinux2_x86_64.tar.gz …
```

Support jammy and amazonlinux2 for toolchain install

---

.github/workflows/swift.yml

#402 will make 5.7 the minimum tools version. 
We need to move CI versions up in order for checks to pass.
- Build on macos-11 with Swift 5.5
- Build on macos-12 with Swift 5.6
- Build on ubuntu-20.04 with Swift 5.6

Update CI Action

---

.github/workflows/swift.yml

Add swift 5.9 to the build action.
The ubuntu runner was only using the installed Swift version, which was 5.8.1 at this pull request; it was never using the matrix provided Swift version. Removed the excessive runs for now.

Add Swift 5.9 to Build Action

---

CHANGELOG.md
Dockerfile
Package.resolved
Package.swift
Sources/CartonHelpers/Async.swift
Sources/CartonHelpers/DefaultToolchain.swift
Sources/CartonHelpers/Version.swift
Sources/CartonKit/Model/Template.swift
Sources/SwiftToolchain/Toolchain.swift
package-lock.json
package.json

This release adds SwiftWasm 5.9 toolchain support, which includes usability with macOS Sonoma beta.
```swift
- checking Swift compiler path: /Users/furby/.carton/sdk/wasm-5.9-SNAPSHOT-2023-08-01-a/usr/bin/swift
- checking Swift compiler path: /Users/furby/.swiftenv/versions/wasm-5.9-SNAPSHOT-2023-08-01-a/usr/bin/swift
- checking Swift compiler path: /Users/furby/Library/Developer/Toolchains/swift-wasm-5.9-SNAPSHOT-2023-08-01-a.xctoolchain/usr/bin/swift
Inferring basic settings...
- swift executable: /Users/furby/Library/Developer/Toolchains/swift-wasm-5.9-SNAPSHOT-2023-08-01-a.xctoolchain/usr/bin/swift
SwiftWasm Swift version 5.9-dev (LLVM 8250a14f5d3ef6a, Swift 57acd8f2a758d01)
Target: arm64-apple-darwin23.0.0
Parsing package manifest:
[debug]: evaluating manifest for 'cosmicportal' v. …
```

Swift 5.9 toolchain & macOS Sonoma beta

---

.github/workflows/swift.yml

https://github.com/swift-actions/setup-swift/issues/591

Stop using the setup-swift action

---

Sources/SwiftToolchain/ToolchainError.swift
Sources/SwiftToolchain/ToolchainManagement.swift

GitHub APIにアクセスして失敗した時、そのレスポンスがログに出力されないため、
以下のように CI でそれが起きた時、問題の詳細が分からず修正が困難です。
https://github.com/swiftwasm/carton/actions/runs/9120974490/job/25079364661?pr=434#step:8:413
ToolchainError に レスポンスボディを含めるようにして、ログに出します。
手元では以下のように出力が得られました。
URL をわざと間違えています。
```
Response from https://api.github.com/repos/swiftwasm/swiftxx/releases/tags/swift-wasm-5.9.2-RELEASE had invalid status 404 with a body of 118 bytes: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/releases/releases#get-a-release-by-tag-name"}
```

ToolchainErrorにレスポンスの内容も含めてログに出す

---

Sources/CartonCLI/Commands/Dev.swift
Sources/CartonKit/Server/Server.swift

現状、CartonFrontend devコマンドを単体で使う事ができません。
devコマンドのwatch機能が、devプラグインから呼び出されることに依存しているからです。
具体的には、devコマンドが変更検知をしてリビルドをする際には、
devプラグインが用意した名前付きパイプを使って依頼するからです。
しかし、 devコマンドが単体で使えると便利です。
devコマンドの サーバ機能の動作だけを単体テストしやすくなるからです。
そこで、devコマンドにwatch対象を指定しなかった場合は、
watch機能を無効化して動作するようにします。
testコマンドが `test.js` を `~/.carton` から配送しようとして失敗しているバグがあります。
この変更を活用して、これを自動テストするつもりです。
watchするときにその対象がターミナルに出力されるが、
その処理をdevコマンドから Server に移す。
実際に watch処理をやっているのは Serverであるため。
こうすると、他の箇所からも Server を利用してwatchする場合にログが出て便利。
なお、現状は他の利用箇所はない。
パイプを受け取るコマンド引数をオプショナルにします。
ただし、watch対象ディレクトリが指定されている場合は省略を禁じます。

`CartonFrontend dev` の watch 機能をオプトインにして、コマンド単体で利用可能にする

---

Tests/CartonCommandTests/CommandTestHelper.swift

テストでは `findSwiftExecutable` という関数が便利に使われていますが、
`swift` コマンド以外のコマンドを探すことができません。
#434 のように他のコマンドも探せると便利です。
`findExecutable` を実装します。
見つからなかった場合には以下のようにエラーメッセージを出します。
```
/Users/omochi/github/swiftwasm/carton/Tests/CartonCommandTests/CommandTestHelper.swift:38: error: -[CartonCommandTests.TestCommandTests testWithNoArguments] : failed: caught error: "Executable foobar was not found: status=1"
```
#434 で curl を使おうとしたらどうやら見つからなかったのですが、
`findExecutable` の実装上エラーログが貧弱で対処しづらそうでした。
#434 の変更をなるべく小さくするため、
この改善だけ単品で切り出したパッチを作りました。

テストで使われている findSwiftExecutable を一般化して findExecutable を実装する

---

Sources/CartonHelpers/Basics/Process/ProcessEnv.swift
Tests/CartonTests/ProcessTests.swift

`CartonHelpers.Process` の環境変数設定機能が壊れています。
これを介して `env` コマンドを実行すると、以下のようなおかしな文字列が得られます。
```
ProcessEnvironmentKey(value: "PATH")=/usr/local/bin:/usr/bin
```
期待される正しい挙動は
```
PATH=/usr/local/bin:/usr/bin
```
です。
このパッチはこのバグを修正します。
また、期待した結果が得られるか確認する自動テストを追加します。
このソースコードは swift-tools-support-core から派生しているようです。
そのため、このプロジェクト独自の変更はメンテナンス性を低下させる恐れがあります。
すでに TSC自体が deprecated だからどうでもいいですかね。

CartonHelpers.Processの環境変数設定機能のバグを直す

---

.github/workflows/swift.yml

`.carton` ディレクトリが CI 上では作成されています。
その結果、本来存在しないはずの `.carton` ディレクトリが存在する事と、
本来参照しないはずの `.carton` ディレクトリを参照するバグ
の2つが組み合わさり、
本来生じるはずの不具合が回避されるという問題が起きています。
これによって #434 で取り組んでいるCIによるバグの検出が失敗し、
バグがないかのように動作してしまっています。
CI で `.carton` を作成する処理を削除します。

`.carton` ディレクトリを CI 上で作成するのをやめる

---

Sources/carton-release/HashArchive.swift

使っていない let 変数があり、警告が出ているので、消します。
ビルド全体において、警告が出るのはここだけなので、これで綺麗になります。
不要な `import WasmTransformer` を消します。
`WasmTransformer` を利用している箇所は他には `Bundle.swift` だけでとても少ないので
整理しておくと依存箇所がわかりやすくて良いと思います。

`HashArchive.swift` の不要なimportとletを消す

---

.github/workflows/swift.yml
Sources/SwiftToolchain/ToolchainManagement.swift

ツールチェーンをインストールするときに GitHub API を利用していますが、
これが CI などではレートリミットに到達して CI が通らなくなってしまうことがあります。
以下は実際にそうなった例です。
https://github.com/swiftwasm/carton/actions/runs/9129608385/job/25104562386?pr=434#step:8:547
なお、このログは #435 によって表示されるようになりました。
GitHub API に対してトークン認証を行うようにします。
トークンは `ToolchainSystem` の引数で与えられる他、
環境変数の `GITHUB_TOKEN` を参照して利用します。
トークン認証が成功していても、そもそも認証していなくても、
ある程度は API が使えるため検証が難しいです。
代わりに、00030d3 でわざと不正なトークンを設定し、認証エラーを引き起こすことで、
通信に正しくトークンが載っていることを確認しました。
mac
```
Swift/ErrorType.swift:200: Fatal error: Error raised at top level: Response from https://api.github.com/repos/swiftwasm/swift/releases/tags/swift-wasm-5.9.2-RELEASE had invalid status 401 with a body of 80 bytes: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
``` …

ツールチェーン取得における GitHub API の利用時に認証をする

---

Sources/CartonKit/Server/HTML.swift

全体は2スペースインデントなのに、metaタグに入るところだけ4スペースになっていたので、直します。

index.htmlのインデントを直す

---

Plugins/CartonPluginShared/README.md

原文だと、
「このディレクトリにはプラグインが共有するソースへのシンボリックリンクが含まれる」
と書いてあります。
しかし実際にはこのディレクトリにはシンボリックリンクは含まれていません。
代わりにソースコードが直接置かれています。
そして、プラグイン達がこのディレクトリ自体をシンボリックリンクで参照しています。
そこで、実態にあった説明文に更新します。

CartonPluginSharedのREADMEを修正する

---

Tests/CartonCommandTests/DevCommandTests.swift
Tests/CartonCommandTests/TestCommandTests.swift

現在 dev server が `test.js` を配送できないバグがあり、
ブラウザでのテストの実行が進行しません。
`carton test` コマンドの自動テストはこの影響でフリーズしてしまうため、
そのようなブラウザのテストを無効化します。
この問題は元々 #420 から発生していましたが、
`.carton` ディレクトリが残っていると発現しないため隠れていました。
#438 によりCI環境からも `.carton` ディレクトリが廃止されたため、
その影響で CI の自動テストが停止しなくなっていました。
無効化においては メッセージを含めた `XCTSkip` を利用することで、
CIログで状況がわかるようにしておくことで、
将来この配送の問題を修正するタスクに取り組むことを見落としにくくします。
#442 の変更によってテストが失敗していました。
テストケースの追従を忘れていたため、修正します。
jsが配送されないバグは #434 で現状を自動テストできるようにしてから修正する計画です。

フリーズしてしまうブラウザテストを無効化する

---

.github/workflows/swift.yml

現在CartonはSwift 5.9.2 をサポート下限としています。
しかし、CIは5.9 (.0) を使っているため、下記の警告が出ています。
```
Swift 5.9.1 or earlier is not supported by carton
```
サポートしていない環境をテストする意味はないので、
テスト環境を5.9.2 に引き上げます。

CIのSwiftバージョンを5.9.2に引き上げる

---

.github/workflows/swift.yml

現在の標準のSwiftバージョンである5.10をCIに追加します。
これによって、CLIツールとしてのcartonが 5.10 で **ビルド** できるかどうかがテストされます。
ただし、ビルド後の **実行** については、実際のところテストされません。
`carton` コマンドはホスト環境で実行されますが、
その先のプラグインとフロントエンドコマンドについては、
cartonが管理・インストールする swift 5.9.2 ツールチェーンが使われるからです。
なお現状、wasmビルドについては `$ swift test` が動かないという既知の問題がありますが、
上述の通りでテストの実行は 5.9.2 が使われるので、
特に問題は生じないはずです。
mac環境は別の作業とします。
上述の通り、 wasmで `$ swift test` は動きません。
ただし、wasm executableは動くので、
`carton-frontend dev` は、 `5.10` でビルドした wasm executable を乗っけて、
同じく `5.10` でビルドした `carton-frontend dev` を直接使って、
起動することが可能です。
このように、 carton によるツールチェーンを迂回して、
直接 frontend を動かす利用方法の自動テストを今後実装するつもりです。

CIのLinux環境にSwift 5.10を追加する

---

Tests/CartonCommandTests/CommandTestHelper.swift

`CommandTestHelper.swift` に書かれたテスト用のユーティリティメソッドが、
`XCTest` のエクステンションとして定義されています。
内容が特に `XCTest` のインスタンスと紐付ける必要がないもので、
設計として不適切なため脱エクステンションします。
将来的にこの辺りのプロセス制御系のコードを、
プロジェクト全体で整理したいので、
その際の変更を小さくする意図もあります。
なお、経緯を調べたところ、最初にこのエクステションを定義した時には、
`self` を参照してそこから `Bundle` を取得するロジックが書かれていたので、
メソッドとして定義するのは合理的です。
https://github.com/swiftwasm/carton/blob/5fe8c8edac087f1ed3de487c327a6621e622d1b1/Tests/CartonCLITests/CommandTestHelper.swift#L181
今はそのメンバはありません。

Stop defining test utilities under XCTest

---

Sources/carton/main.swift

`carton.makeTemporaryFile` にバグがありました。
引数に渡された prefix が使われていません。
引数に渡された suffix が使われていません。
そもそも下請けの `mkstemp` はsuffixが使えません。
ファイルを作る関数なのに文言がディレクトリになっています。
修正のついでに以下の改善をします。
ディレクトリを省略可能にし、デフォルトで `NSTemporaryDirectory` を使うようにします。
用途から考えると妥当で便利だと思います。
`errno` を参照してエラー文言に添えます。
失敗してもクラッシュではなく例外を投げます。
carton, プラグイン, フロントエンドで様々なユーティリティが多重に実装されています。
これを統合したいと思っていて、
その前準備としてこの関数の仕様を整えました。

Bug fix on makeTemporaryFile

---

Package.swift
Sources/CartonHelpers/Basics/Process/Process.swift
Sources/CartonHelpers/Basics/Thread.swift
Sources/CartonKit/Utilities/FSWatch.swift
Sources/TSCLibc/libc.swift
Sources/TSCclibc/include/TSCclibc.h
Sources/TSCclibc/include/module.modulemap
Sources/TSCclibc/include/process.h
Sources/TSCclibc/process.c.c

#458 を `CartonHelpers.Process` で実装しようとしたところ、
プロセスの ワーキングディレクトリを設定する機能が実装されていませんでした。
最新の `TSC.Process` であれば実装されていたので、
ソースコードをコピペして追従します。
ただ、新たに `TSCLibc` と `TSCclibc` モジュールへの参照が追加されていたので、
これらの追加も追従します。
また、依存として `TSC.Thread` も必要になっていたので、これも移植します。
`TSC.Process` は以下のバージョンと一致させています。
https://github.com/apple/swift-tools-support-core/blob/990afca47e75cce136d2f59e464577e68a164035/Sources/TSCBasic/Process/Process.swift
このファイルのコミットヒストリーによればこれが最新です。
https://github.com/apple/swift-tools-support-core/commits/990afca47e75cce136d2f59e464577e68a164035/Sources/TSCBasic/Process/Process.swift
---
カレントディレクトリ設定が必要になるロジックはこの部分です。
https://github.com/swiftwasm/carton/blob/bb9a91ce0bc19e84f273b88eb3bf95d6108ffdad/Tests/CartonCommandTests/CommandTestHelper.swift#L71

Import upstream changes of `TSC.Process` 

---

Sources/CartonHelpers/ProcessEx.swift
Tests/CartonCommandTests/BundleCommandTests.swift
Tests/CartonCommandTests/CommandTestHelper.swift
Tests/CartonCommandTests/DevCommandTests.swift
Tests/CartonCommandTests/TestCommandTests.swift

#458 と同じ目的を、別のアプローチで実装します。
ストリームとキャプチャを同時にするために、
`Foundation.Process` を利用しているところを変更し、
`CartonHelpers.Process` を使うようにします。
これには `outputRedirection:` という機能があるため、
これを活用してクロージャでデータフローを実装します。

Stream command outputs while capturing them for testing

---

Sources/CartonDriver/CartonDriverCommand.swift

`Process.checkRun` が実装されていますが、少し変です。
`forwardExit` フラグが指定されている場合に、
`terminationHandler` 経由で `exit` していますが、
それとは別に `waitUntilExit()` の後にも `exit` するフローがあります。
これだと `exit` する経路が2つあって、
どちらを通るかは並行処理次第であり不安定に見えます。
そもそも `waitUntilExit()` している関数なので、
そこから復帰した後に `exit` へ入れば良いので、
`terminationHandler` を使わないシンプルな形に書き換えます。
---
既存のコードで `waitUntilExit` の後に書いてある `exit` は、
ステータスコードが失敗なら突入するようになっているので、
`forwardExit` の機能としては壊れています。
よってこれは `forward` しない場合の機能のようです。
実際にこちらが使われるのは、
`carton test` に2つあり、
plugin に対して `internal-get-build-command` を呼ぶところと、
受け取ったそのビルドコマンドを実行するところです。
この2箇所については、
もしコマンドが失敗した時はステータスコードを転送して即死するのではなく、
制御ロジックとして例外を投げる方が望ましいと思います。
その方が失敗した時に状況が理解しやすいです。
これらのコマンドは driver が変身してるわけではないからです。
---
出力例です。
test経由でビルドが始まったときに C-c を押して殺しています。
例外のメッセージを使って、
死んだコマンドのコマンドラインがコンソールに出せるので、 …

Fix bugs in `Process.checkRun` of CartonDriver

---

Package.swift
Plugins/CartonBundlePlugin/CartonCore
Plugins/CartonDevPlugin/CartonCore
Plugins/CartonTestPlugin/CartonCore
Sources/CartonCore/Environment.swift
Sources/CartonCore/README.md
Sources/CartonFrontend/Commands/CartonFrontendTestCommand.swift
Sources/CartonKit/Utilities/EnvironmentEx.swift
Tests/CartonCommandTests/CommandTestHelper.swift
Tests/CartonCommandTests/DevCommandTests.swift
Tests/CartonCommandTests/FrontendDevServerTests.swift
Tests/Fixtures/DevServerTestApp/.gitignore
Tests/Fixtures/DevServerTestApp/Package.swift
Tests/Fixtures/DevServerTestApp/Sources/app/main.swift
Tests/Fixtures/DevServerTestApp/Sources/app/style.css

#434 のやり直しです
frontend の devserver を単体でテストします。
通常、 `carton` コマンドを利用すると、
`carton` が管理するツールチェーンを通して、
対象プロジェクトと plugin, frontend がビルドされ、
plugin 経由で実行されます。
この一連の流れは `DevCommandTests` でテストされています。
それゆえにツールチェーンのダウンロード処理なども内部で行われるため、
サーバ起動の待機秒数を多く取っていたりして効率が悪いです。
また、plugin以下の実行は、
その管理されたツールチェーンでビルドしたものしか実行されません。
driver や plugin のロジックの影響を受けずに、
frontendだけを対象としたテストは、
driver 経由のテストよりも安定性を高められます。
また、dev server 起動までの事前処理を制御できるので、
起動の待機秒数を短くできます。
また、さまざまなツールチェーンでのビルド・実行をテストできます。
バイナリの準備ではToolchainSystemを使いますが、
dev serverの起動では現在のSwiftを使います。
テストでは、
dev serverの機能である、
インデックスページ、
エントリポイントJS、
メインWasmバイナリ、
ユーザ定義リソース
の配送を確認します。
将来的にはdev serverとJSが通信していることもテストしたいです。
大きな変更になるためコミットを丁寧に分割しています。
`Environment` に書かれたビルドオプションの構成ロジックを、
従来のプラグインと、テストコードで共有するため、新しく `CartonCore` モジュールを作ります。
CartonHelper …

Add unit test for dev server

---

Tests/CartonCommandTests/TestCommandTests.swift

This reverts commit f6f17127334c9a76108f0616ee924334c9c2d878 in https://github.com/swiftwasm/carton/pull/449.

Revert "Skips browser testing due to freezing"

---

Tests/CartonCommandTests/BundleCommandTests.swift
Tests/CartonCommandTests/Testable.swift

`AbsolutePath.ls` をしなくても、 `FileSystem.getDirectoryContents` や `FileSystem.traverseRecursively` があります。
テスト用のやり方を用意してもコード短縮の恩恵は少ないです。
また、 `ls` という名前なのに再帰的に中身を取り出す挙動は予測しづらいです。
必要ない道具は消したほうが、コードベースを把握しやすくなります。
また、 `ls` は `String` を返しますが、
ここではファイルパスであることが確定しているので、
`AbsolutePath` を返すAPIの方が、
その先のデータ操作で様々なメソッドが使えて便利です。
使わなくても十分に整ったテストが書けるので消します。
#468 でもこの件に少し触れています。

Remove test utility `ls`

---

Tests/CartonCommandTests/CommandTestHelper.swift
Tests/CartonCommandTests/DevCommandTests.swift
Tests/CartonCommandTests/FrontendDevServerTests.swift

以下でCIがこけました
https://github.com/swiftwasm/carton/pull/469#issuecomment-2124942557
おそらくタイミング問題で、サーバが立ち上がっていなかっただけなので、
待ってからリトライすれば直ります。
ここで、最初の待ち時間は短くして、
失敗しとの待ち時間は長くしたいです。
そこで既存の `withRetry` を改善して指定できるようにします。

Add granular configuration for retrying wait time in test

---

Package.swift
Sources/CartonFrontend/Commands/TestRunners/BrowserTestRunner.swift
Sources/CartonHelpers/Retry.swift
Sources/WebDriver/CommandWebDriverService.swift
Sources/WebDriver/CurlWebDriverHTTPClient.swift
Sources/WebDriver/RemoteWebDriverService.swift
Sources/WebDriver/URLSessionAsync.swift
Sources/WebDriver/URLSessionWebDriverHTTPClient.swift
Sources/WebDriver/WebDriverClient.swift
Sources/WebDriver/WebDriverError.swift
Sources/WebDriver/WebDriverHTTPClient.swift
Sources/WebDriver/WebDriverService.swift
Tests/CartonCommandTests/CommandTestHelper.swift
Tests/CartonCommandTests/DevCommandTests.swift
Tests/WebDriverTests/WebDriverClientTests.swift

#473 のために、WebDriver を利用したい。
WebDriver の実装は `WebDriverClient.swift` にクライアント実装、
`CartonFrontendTestCommand.swift` にドライバの選択処理などが書かれている。
WebDriver関連の実装をモジュールにまとめて、
テストなどから再利用しやすいようにする。
`WebDriverClient` において、
curl が使える状況では 引数で受け取った `URLSession` を捨てるようになっていた。
また、 curl と URLSession の抽象化のために `WebDriverHTTPClient` を定義していた。
`URLSession` はこれに直接準拠していた。
`WebDriverClient` がHTTP通信に使う依存物は、
ユーザー側から注入をコントロールできるようにした方が良い。
そのほうが、個別の実装をテストしたり、
自動選択したりする挙動を使う意図が明確なコードを書くことができる。
しかし、 `WebDriverHTTPClient` のメソッドは、
`URLSession` の既存のメソッドと紛らわしいし、
仕様がこの用途に特化しているため、他の場所から使われたくないため、
`URLSession` への準拠させたくはない。
そこで、 `URLSessionWebDriverHTTPClient` というアダプタを用意する。
また、 `Curl` 型も `CurlWebDriverHTTPClient` にリネームする。
さらに、従来の選択挙動は `WebDriverHTTPClients.find` として利用可能にする。
`URLSessionWebDriverHTTPClient` は Linux では全く動かないことがわかった。 …

Combine the WebDriver setup process into WebDriverService and make it easier to reuse

---

Sources/CartonFrontend/Commands/CartonFrontendDevCommand.swift
Sources/CartonFrontend/Commands/CartonFrontendTestCommand.swift
Sources/CartonFrontend/Commands/TestRunners/BrowserTestRunner.swift
Sources/CartonKit/Server/Server.swift

dev server は `--host` で指定したアドレスで待ち受けします。
仮に `--host` がデフォルトの 127.0.0.1 の場合、
同一ホスト上から `http://127.0.0.1:8080` へのアクセスでなければ接続できません。
ホストのLAN IPが 192.168.1.2 だったとして、 `http://192.168.1.2:8080` では接続できません。
また、同一LAN の他のマシンやスマートフォンからも接続できません。
ウェブアプリ開発ではスマホを対象にしたりするのでこれは不便です。
`--host` で 192.168.1.2 を指定すれば、それで接続できますが、
この場合は同一ホストであっても `127.0.0.1` から接続できません。
状況に応じて使い分ける必要があり、面倒です。
また、Docker内部で起動する場合、
コンテナのネットワークアドレスが必要ですが、
これを把握するのは多少面倒です。
こういった状況のために、ソケットインターフェースには待ち受けアドレスとして `0.0.0.0` が指定できます。
これはそのホストのあらゆるアドレスからの接続を受け入れる特別な設定です。
これで起動すれば、接続元に応じたホストのアドレスを指定するだけで良いので簡単です。
知る限りでは、 `npx serve` コマンドや `nc` コマンド、 vitejs の devサーバ なども、
デフォルトではこのモードで待ち受けおり、一般的です。
そこで、新たに `--bind` オプションを導入し、待ち受けアドレスを指定できるようにしつつ、
そのデフォルト値として `0.0.0.0` を指定します。
`--host` オプションのデフォルト値は `127.0.0.1` を使うのをやめて、
`--bind` …

Add --bind to specify serving address with relaxed default (0.0.0.0)

---

Sources/CartonFrontend/Commands/CartonFrontendBundleCommand.swift
Tests/CartonCommandTests/BundleCommandTests.swift

The `-Xwasm-opt` option allows users to pass extra flags to `wasm-opt` optimizer. This is especially useful for enabling some future features like `--enable-threads`.

Add `-Xwasm-opt` option to `bundle` subcommand

---

Plugins/CartonBundlePlugin/CartonBundlePluginCommand.swift
Plugins/CartonDevPlugin/CartonDevPluginCommand.swift
Plugins/CartonPluginShared/PluginShared.swift
Plugins/CartonTestPlugin/CartonTestPluginCommand.swift
Sources/CartonCore/CartonCoreError.swift
Sources/CartonCore/FoundationProcessEx.swift
Sources/CartonDriver/CartonDriverCommand.swift
Sources/CartonFrontend/Commands/CartonFrontendBundleCommand.swift
Sources/CartonHelpers/ProcessEx.swift
Tests/CartonCommandTests/CommandTestHelper.swift
Tests/CartonCommandTests/DevCommandTests.swift

driver, plugin, test では Foundation.Process が使われています。
frontend, test では CartonHelpers(TSC).Process が使われています。
そして、driver と plugin と frontend の3箇所で、
それぞれ Process の拡張が行われています。
そのためプロジェクトを横断的に読み書きするのが難しくなっています。
同じことをやりたくても書き方が違ったり、
同じメソッド名なのに挙動が違ったりもするからです。
また、同じものが重複して実装されている部分もあります。
このパッチではそういったユーティリティを整理して統一・共通化します。
`TSC.Process` と一緒に定義すれば良いからです。
`CartonCore` はdriver, plugin の両方からアクセスできるモジュールとして最近定義されました。
これは TSC と Foundation の両方で局所的に書かれているので、
どちらもメソッドとして定義します。
ついでにバグがあったので直します。
`setSignalForwarding` を `SIGINT` と `SIGTERM` について設定する操作はよく出てくるので、
このメソッド名で統一します。
なお、元々はこれに `terminationHandler` による `exit` の転送が書いてありましたが、
これは削除しました。
`waitUntilExit` と一緒に使っていて意味がなかったからです。
`waitUntilExit` は `terminationHandler` の完了を待たないので、
そもそもレースコンディションが起きていました。
`waitUntilExit` の後で exit forward すれば十分で、その方が安定します。 …

Refactor utilities under Foundation.Process and CartonHelpers.Process and share implementations

---

Package.swift
Plugins/CartonDevPlugin/CartonDevPluginCommand.swift
Plugins/CartonTestPlugin/CartonTestPluginCommand.swift
Sources/CartonCore/CartonCoreError.swift
Sources/CartonDriver/CartonDriverCommand.swift
Sources/CartonFrontend/Commands/CartonFrontendDevCommand.swift
Sources/CartonFrontend/Commands/CartonFrontendTestCommand.swift
Sources/CartonFrontend/Commands/TestRunners/BrowserTestRunner.swift
Sources/CartonKit/Server/Server.swift
Sources/CartonKit/Server/ServerHTTPHandler.swift
Tests/CartonCommandTests/CommandTestHelper.swift
Tests/CartonCommandTests/DevCommandTests.swift
Tests/CartonCommandTests/FrontendDevServerTests.swift
Tests/Fixtures/EchoExecutable/Package.swift

DevCommandTests と FrontendDevServerTests では、テストケースの中で dev server を起動して、
それと通信して挙動を検証しています。
しかし、テスト実行中に別のターミナルで dev server が起動していたり、
全く別のプロセスがポートを使用していたり、
開発中のバグの影響で、以前起動したテスト用のプロセスがゾンビ化して生き残っていたりすると、
テストしようとした dev server が待ち受けポートを利用できずに起動に失敗してしまいます。
これは実際に、`SIGTERM` を `SIGINT` に意図せず変換してしまうバグを修正した時に、
`SIGTERM` のハンドルがされずにゾンビプロセスが生まれることによって、
CIがわかりづらい壊れ方をするなどの現象を引き起こしました。
起動に失敗したことによりテストが停止すれば良いのですが、
この起動の失敗を検出するのは困難です。
`carton dev` コマンドは swift ツールチェーンのインストールなども行うため、
プロセスが正常に実行されているのか、
将来的にサーバの起動に失敗する状況にあるかわからないからです。
起動時間が読めないこともあって、テストケースはHTTPリクエストをしばらくリトライします。
そして、別の理由で先に存在していた dev server がいた場合は、
テストプロセスのHTTP通信が成功してしまうため、
テストが誤って成功したり、予期し得ないレスポンスが返って意味不明な失敗をしたりします。
また、ゾンビプロセスが残っていることがわかった時、
それを特定して kill するまでの手順も多少面倒です。
macOS は `$ lsof -i -P` の実行に何故か結構待ち時間があります。
テストを安定させるために、 …

Verify if tests communicate with just spawned dev server

---

Plugins/CartonDevPlugin/CartonDevPluginCommand.swift
Sources/CartonFrontend/Commands/CartonFrontendDevCommand.swift
Sources/CartonKit/Server/Server.swift

devコマンドはファイルの変更があるとリビルドをしますが、
この時、変更によってソースコードが壊れた場合、コンパイルに失敗することがあります。
しかし、プラグインはそれをフロントエンドに伝えていないため、
コンパイルに失敗したにも関わらず、
`Build completed successfully` と出力してからブラウザをリロードさせます。
ユーザがコードの編集中にこれが生じた場合、
successの表示と共にブラウザがリロードされたので、
ユーザは編集結果がブラウザにホットリロードされたと期待するでしょう。
しかし実際にはバイナリが更新されていないため、
動作確認がうまくいかず混乱するでしょう。
コンパイルエラーが出ていることは、
ターミナルの少し上を見なければわからず、
気づかない事があるでしょう。
プラグインからフロントエンドにビルドが成功したかどうかを伝え、
失敗した場合にはそれを表示して、ブラウザのリロードはスキップします。
以下に変更前後の出力の変化を掲載します。
余計な空行も削除しています。
**変更前, リビルド成功時**
```
These paths have changed, rebuilding...
- /Users/omochi/github/swiftwasm/carton/Tests/Fixtures/SandboxApp/Sources/app
- /Users/omochi/github/swiftwasm/carton/Tests/Fixtures/SandboxApp/Sources/app
Build completed successfully
```
**変更前, リビルド失敗時**
```
These paths have changed, rebuilding...
- …
```

Skip hot-reloading if build fails

---

Sources/CartonHelpers/DefaultToolchain.swift

現在、cartonの用意するツールチェーンのバージョンは固定でハードコードされています。
これは概ね現在の最新安定版を追従するように更新されています。
しかし、ユーザの開発環境はそれより古いものからまだアップグレードできていなかったり、
逆にリリース前の超最新版を使いたいこともあります。
そのような場合に、ソースコードの編集で使われる言語バージョンと、
cartonがwasmビルドで利用する言語バージョンが異なってしまいます。
対策方法として、`.swift-verison` ファイルを用意することで、
cartonが利用するバージョンを切り替えることができます。
しかしこれを使うまでもなく、
ユーザが期待するcartonに使って欲しいであろうバージョンは、
ユーザが `$ swift run carton bundle` するときに叩いている swift のバージョンでしょう。
ファイルで設定することなく、このように期待されるバージョンに切り替われば便利です。
このパッチでは、そのようにデフォルトを切り替えるように変更します。
cartonはswiftpmで依存pluginとして導入することが想定されているため、
そのSwiftのバージョンはcartonコードの中で `#if compiler` を判別することができます。
実装ではこれを使います。
事前に相談した会話:
https://discord.com/channels/291054398077927425/383442648012423179/1248990244888641648

Adaptive default toolchain version based on Swift version on builder

---

.github/workflows/swift.yml
ci/mac/install-swift.bash

macのCIにSwift6.0を追加します。
そのままだと動かないので↓のハックをCIでインストールするときに適応します。
https://github.com/apple/swift/issues/73327#issuecomment-2120481479
6.0でビルドされたcartonがインストールするSwiftは5.10のままです。
これは別パッチにして後で出します。 #484 で作業しています。
そのため、この変更では、
cartonコードベースがSwift6.0でビルドできるかどうかを検証するだけで、
自動テストで動作検証する時の挙動は5.10のままです。
PRを提出するときに先頭コメントを書き換えました。
後続コメントは作業中のメモなので無視してください。

Add Swift 6.0 CI for building carton for macOS 

---

.github/workflows/swift.yml
Sources/CartonFrontend/Commands/CartonFrontendBundleCommand.swift
Sources/CartonHelpers/DefaultToolchain.swift

Linux の CI に Swift 6.0 を追加します。
#481 がマージ済みなので、Carton実行時も Swift 6.0 を使います。
---

Add Swift 6.0 CI for Linux

---

Sources/CartonHelpers/Process+run.swift

Otherwise, the stdout/stderr output begins on the same line as the command-line logging output, which can be confusing.

Newline after command-line logging output

---

.github/workflows/swift.yml
Sources/CartonCore/Environment.swift
Sources/CartonHelpers/DefaultToolchain.swift

It's fixed in the main branch and cherry-picked to the 6.0 branch.
See https://github.com/apple/swift/pull/74277

Remove the workaround for the linker issue in Swift 6.0

---

Sources/CartonFrontend/Commands/TestRunners/CommandTestRunner.swift

It was broken in the latest wasmtime release 22 https://github.com/swiftwasm/carton/actions/runs/9607328437/job/26498300308#step:8:2365

Put `--dir` wasmtime option before the test file path

---

Package.swift
Sources/CartonKit/Server/Server.swift
Sources/CartonKit/Server/ServerHTTPHandler.swift
Tests/Fixtures/TestApp/Package.resolved

Carton won't be a library, so we don't need a centralized logging system. Removing a dependency speeds up the build

Remove swift-log dependency

---

Plugins/CartonTestPlugin/CartonTestPluginCommand.swift

https://github.com/swiftlang/swift-package-manager/pull/8254 introduced a change to produce `.xctest` files for test products instead of `.wasm` files. This change updates the CartonTestPlugin to support both formats and use the `.xctest` file if it is available.

Support the latest SwiftPM producing .xctest for test products
