swiftwasm/carton

Sources/SwiftToolchain/Toolchain.swift
Sources/SwiftToolchain/ToolchainManagement.swift
TestApp/Sources/TestApp/main.swift

Automatically link Foundation w/ destination.json

---

Sources/SwiftToolchain/ToolchainManagement.swift
Sources/carton/Commands/Local.swift
Sources/carton/Commands/SDK.swift
Sources/carton/Commands/Versions.swift

Support `carton sdk local` subcommand. #15

Implement `carton sdk local` subcommand

---

Sources/SwiftToolchain/Package.swift
Sources/SwiftToolchain/Toolchain.swift
Sources/carton/Commands/Init.swift
Sources/carton/Commands/ListTemplates.swift
Sources/carton/Model/Project.swift
Sources/carton/Model/Template.swift

This adds basic `carton init` support:
```
carton init HelloWorld
```
It also supports templates:
```
carton init --list-templates
carton init HelloWorld --template tokamak
```

Add `carton init` command

---

README.md

This should somewhat alleviate the beta 3 issues reported here: https://github.com/swiftwasm/carton/issues/65

Warn against Xcode 12 betas in `README.md`

---

.swiftformat
.swiftlint.yml
Sources/SwiftToolchain/FileDownloadDelegate.swift
Sources/SwiftToolchain/ToolchainManagement.swift
Sources/carton/Model/Template.swift
Sources/carton/Server/Server.swift

Resolve #7 as described in https://github.com/vapor/vapor/issues/2451.
Additionaly, new formatting is applied with the new version of SwiftFormat.

Close WebSocket connections after HTTP server exits

---

.gitignore
Sources/SwiftToolchain/Toolchain.swift
Sources/carton/Commands/Package.swift

This allows using swift-package in the selected toolchain like
```
$ carton package generate-xcodeproj
```

Add carton package cmd

---

package-lock.json
package.json

Update node.js dependencies, including wasmer.js

---

Sources/CartonHelpers/TerminalController.swift
Sources/SwiftToolchain/Package.swift
Sources/SwiftToolchain/Toolchain.swift
Sources/carton/Commands/Bundle.swift
Sources/carton/Server/Application.swift

Implement resources copying in `carton bundle`

---

Sources/carton/Commands/Dev.swift
Sources/carton/Server/Application.swift
Sources/carton/Server/HTML.swift
Sources/carton/Server/Server.swift
entrypoint/dev.js

Running `carton-release` also changed bundle.js's hash, so I just didn't commit the static resources.

Allow changing dev server's port

---

Package.resolved
Package@swift-5.2.swift

Add Splash dependency to 5.2 package manifest

---

.vscode/tasks.json
Package.resolved
Package.swift
Package@swift-5.2.swift
Sources/CartonHelpers/ProcessRunner.swift
Sources/SwiftToolchain/Builder.swift
Sources/SwiftToolchain/Toolchain.swift
Sources/carton/Commands/Dev.swift
Sources/carton/Server/Server.swift

Add separate Builder class, use WasmTransformer

---

.dockerignore
.github/workflows/swift.yml
Dockerfile
README.md

Add Dockerfile, mention the Docker image in `README.md`

---

README.md

Also update the `carton test` section.

Mark all commands as implemented in `README.md`

---

Sources/SwiftToolchain/Package.swift
Sources/SwiftToolchain/Toolchain.swift
Tests/CartonTests/StackTraceTests.swift

This will unblock making CI work in https://github.com/TokamakUI/Tokamak/pull/333

Fix parsing system targets in `Package.swift`

---

Sources/SwiftToolchain/Toolchain.swift

Resolves https://github.com/swiftwasm/carton/issues/268.

Add ICU linker flags to all build invocation

---

Dockerfile
Sources/CartonCLI/Commands/Bundle.swift
Sources/CartonCLI/Commands/Dev.swift
Sources/CartonCLI/Commands/Options.swift
Sources/CartonCLI/Commands/Test.swift
Sources/SwiftToolchain/BuildFlavor.swift
Sources/SwiftToolchain/Toolchain.swift
Tests/CartonCommandTests/BundleCommandTests.swift

Close https://github.com/swiftwasm/carton/issues/277

Add -Xswiftc option for each build commands

---

Sources/CartonKit/Server/Server.swift

Actor isolated methods must not block the current thread, so Vapor
server's start method is not compatible in Concurrency context.
Resolve https://github.com/swiftwasm/carton/issues/295

Fix watcher blocked by Vapor `run()`

---

Dockerfile

Close https://github.com/swiftwasm/carton/issues/393

Fix the default docker command arguments

---

CHANGELOG.md
Plugins/CartonBundle/Plugin.swift
Sources/CartonCLI/Commands/Bundle.swift
Sources/CartonHelpers/Version.swift
package-lock.json
package.json

Hotfix 1.0.1

---

.github/workflows/swift.yml
Brewfile

僕が入れてしまった余計な変更
https://github.com/swiftwasm/carton/pull/444#discussion_r1605958807
を取り除きます。
間違っているコマンドを直します。
それぞれのステップにより明瞭なタイトルをつけます。

CIスクリプトのミスを修正しつつ、わかりやすいタイトルをつける

---

Sources/CartonKit/Server/ServerHTTPHandler.swift

The server served `~/.carton/static` directory but we no longer use the directory. Instead, we now serve the entrypoint from in-memory buffer.
Test suites will be added by https://github.com/swiftwasm/carton/pull/434

Fix dev server to serve entrypoint file
